export const attackSprites = {
    "normal": require("@/assets/images/attacks/normal-attack.png"),
    "fire": require("@/assets/images/attacks/fire-attack.png"),
    "water": require("@/assets/images/attacks/water-attack.png"),
    "electric": require("@/assets/images/attacks/electric-attack.png"),
    "grass": require("@/assets/images/attacks/grass-attack.png"),
    "ice": require("@/assets/images/attacks/ice-attack.png"),
    "fighting": require("@/assets/images/attacks/fighting-attack.png"),
    "poison": require("@/assets/images/attacks/poison-attack.png"),
    "ground": require("@/assets/images/attacks/ground-attack.png"),
    "flying": require("@/assets/images/attacks/fly-attack.png"),
    "psychic": require("@/assets/images/attacks/psychic-attack.png"),
    "bug": require("@/assets/images/attacks/bug-attack.png"),
    "rock": require("@/assets/images/attacks/rock-attack.png"),
    "ghost": require("@/assets/images/attacks/ghost-attack.png"),
    "steel": require("@/assets/images/attacks/steel-attack.png"),
    "dragon": require("@/assets/images/attacks/dragon-attack.png"),
    "dark": require("@/assets/images/attacks/dark-attack.png"),
    "fairy": require("@/assets/images/attacks/fairy-attack.png"),
};
