export const attackSprites = {
    "normal": require("@/assets/images/battle/normal-attack.png"),
    "fire": require("@/assets/images/battle/fire-attack.png"),
    "water": require("@/assets/images/battle/water-attack.png"),
    "electric": require("@/assets/images/battle/electric-attack.png"),
    "grass": require("@/assets/images/battle/grass-attack.png"),
    "ice": require("@/assets/images/battle/ice-attack.png"),
    "fighting": require("@/assets/images/battle/fighting-attack.png"),
    "poison": require("@/assets/images/battle/poison-attack.png"),
    "ground": require("@/assets/images/battle/ground-attack.png"),
    "flying": require("@/assets/images/battle/fly-attack.png"),
    "psychic": require("@/assets/images/battle/psychic-attack.png"),
    "bug": require("@/assets/images/battle/bug-attack.png"),
    "rock": require("@/assets/images/battle/rock-attack.png"),
    "ghost": require("@/assets/images/battle/ghost-attack.png"),
    "steel": require("@/assets/images/battle/steel-attack.png"),
    "dragon": require("@/assets/images/battle/dragon-attack.png"),
    "dark": require("@/assets/images/battle/dark-attack.png"),
    "fairy": require("@/assets/images/battle/fairy-attack.png"),
};
